export const privacyPolicyText = `
# Privacy Policy for Noble Kode

**Last Updated: May 22, 2025**

## Our Commitment to Your Privacy

At Noble Kode, we value your privacy and are committed to protecting your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website noblekode.com, including any other media form, media channel, mobile website, or mobile application related or connected to Noble Kode (collectively, the "Site").

Please read this privacy policy carefully. If you do not agree with the terms of this privacy policy, please do not access the site.

## Information We Collect

### Personal Data

We may collect personal identification information from users in various ways, including, but not limited to, when users visit our site, register on the site, fill out a form, and in connection with other activities, services, features, or resources we make available on our Site. Users may be asked for, as appropriate:

- Name
- Email address
- Phone number
- Company name
- Job title

### Non-Personal Data

We may collect non-personal identification information about users whenever they interact with our Site. This may include:

- Browser name
- Type of computer or device
- Technical information about users' means of connection to our Site
- Operating system
- Internet service providers
- Other similar information

### Cookies and Tracking Technologies

Our Site may use "cookies" to enhance user experience. Users' web browsers place cookies on their hard drive for record-keeping purposes and sometimes to track information about them. Users may choose to set their web browser to refuse cookies or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.

We use cookies, pixels, and other technologies (collectively "cookies") to recognize your browser or device, learn more about your interests, provide you with essential features and services, and for additional purposes including:

- Recognizing you when you sign in to use our services
- Keeping track of your specified preferences
- Conducting research and diagnostics to improve our content, products, and services
- Preventing fraudulent activity
- Improving security
- Delivering content, including ads, relevant to your interests
- Reporting, which allows us to measure and analyze the performance of our services

### Meta Pixel

Our website uses Meta Pixel, a web analytics and advertising service provided by Meta Platforms, Inc. Meta Pixel uses cookies to help us analyze how users use our site and to enhance our ability to serve targeted advertisements to people who may be interested in our services. The information generated by the Meta Pixel about your use of our website (including your IP address) will be transmitted to and stored by Meta on servers in the United States.

Meta Pixel helps us understand the effectiveness of our advertising campaigns on Meta platforms (Facebook and Instagram) and allows us to retarget users who have already visited our website. This means that we may show our ads to you on Meta platforms after you have visited our website.

## How We Use Your Information

Noble Kode may collect and use users' personal information for the following purposes:

- **To improve customer service** - Information you provide helps us respond to your customer service requests and support needs more efficiently.
- **To personalize user experience** - We may use information in the aggregate to understand how our users as a group use the services and resources provided on our Site.
- **To improve our Site** - We may use feedback you provide to improve our products and services.
- **To process payments** - We may use the information users provide about themselves when placing an order only to provide service to that order. We do not share this information with outside parties except to the extent necessary to provide the service.
- **To run a promotion, contest, survey or other Site feature** - To send users information they agreed to receive about topics we think will be of interest to them.
- **To send periodic emails** - We may use the email address to send user information and updates pertaining to their order. It may also be used to respond to their inquiries, questions, and/or other requests. If the user decides to opt-in to our mailing list, they will receive emails that may include company news, updates, related product or service information, etc. If at any time the user would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.
- **For advertising and marketing** - We may use your information to deliver advertisements and marketing communications to you about our services that may be relevant to your interests. This includes using your data for Meta Business advertising purposes.

### Legal Basis for Processing (For EEA Users)

If you are an individual in the European Economic Area (EEA), we collect and process information about you only where we have legal bases for doing so under applicable EU laws. The legal bases depend on the services you use and how you use them. This means we collect and use your information only where:

- We need it to provide you services, including to operate the services, provide customer support, personalized features, and to protect the safety and security of the services;
- It satisfies a legitimate interest (which is not overridden by your data protection interests), such as for research and development, to market and promote the services, and to protect our legal rights and interests;
- You give us consent to do so for a specific purpose; or
- We need to process your data to comply with a legal obligation.

## How We Share Your Information

We do not sell, trade, or rent users' personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates, and advertisers for the purposes outlined above.

### Third-Party Service Providers

We may use third-party service providers to help us operate our business and the Site or administer activities on our behalf, such as sending out newsletters or surveys. We may share your information with these third parties for those limited purposes provided that you have given us your permission.

These third-party service providers include:

- **Meta Platforms, Inc.** - We share information with Meta through the Meta Pixel for advertising and analytics purposes.
- **Google Analytics** - We use Google Analytics to help us understand how our customers use the Site.
- **Payment processors** - We use third-party payment processors to handle financial transactions on our Site. These processors have their own privacy policies that govern how they use your personal information.
- **Email marketing services** - We may use third-party email marketing services to send newsletters and promotional emails.

### Legal Requirements

We may disclose your information if required to do so by law or in the good-faith belief that such action is necessary to:

- Comply with a legal obligation
- Protect and defend the rights or property of Noble Kode
- Prevent or investigate possible wrongdoing in connection with the Site
- Protect the personal safety of users of the Site or the public
- Protect against legal liability

### Business Transfers

If Noble Kode is involved in a merger, acquisition, or sale of all or a portion of its assets, you will be notified via email and/or a prominent notice on our Site of any change in ownership or uses of your personal information, as well as any choices you may have regarding your personal information.

## Your Rights and Choices

### Access, Correction, and Deletion

You have the right to access, correct, or delete your personal information that we collect and maintain. To request access to, correction, or deletion of your personal information, please contact us at privacy@noblekode.com. We will respond to your request within a reasonable timeframe.

### Data Retention

We will retain your personal information only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your information to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our policies.

### Opt-Out Rights

You can stop receiving promotional emails from us by following the unsubscribe instructions included in every email we send.

You can opt-out of Meta Pixel tracking by using browser add-ons or extensions specifically designed to block tracking scripts. You can also visit Meta's Ad Preferences to learn more about the information Meta collects and control how it's used.

Most web browsers are set to accept cookies by default. If you prefer, you can usually choose to set your browser to remove or reject browser cookies. Please note that if you choose to remove or reject cookies, this could affect the availability and functionality of our Site.

### Do Not Track Signals

Some browsers have a "Do Not Track" feature that lets you tell websites that you do not want to have your online activities tracked. At this time, we do not respond to browser "Do Not Track" signals, but we do provide you the option to opt out of interest-based advertising as described above.

### Children's Privacy

Our Site is not intended for children under the age of 13. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we can take necessary actions.

### Your California Privacy Rights

California Civil Code Section 1798.83 permits users of our Site that are California residents to request certain information regarding our disclosure of personal information to third parties for their direct marketing purposes. To make such a request, please send an email to privacy@noblekode.com.

### Your European Privacy Rights

If you are located in the European Economic Area (EEA), you have certain rights under the General Data Protection Regulation (GDPR), including:

- The right to access your personal data
- The right to rectify inaccurate personal data
- The right to erasure of your personal data
- The right to restrict processing of your personal data
- The right to data portability
- The right to object to the processing of your personal data

To exercise these rights, please contact us at privacy@noblekode.com. We will respond to your request within 30 days.

## International Data Transfers

Your information, including personal data, may be transferred to and maintained on computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.

If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including personal data, to the United States and process it there. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.

Noble Kode will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your personal data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.

## Security of Your Information

We adopt appropriate data collection, storage, and processing practices and security measures to protect against unauthorized access, alteration, disclosure, or destruction of your personal information, username, password, transaction information, and data stored on our Site.

However, please be aware that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.

## Changes to This Privacy Policy

Noble Kode has the discretion to update this privacy policy at any time. When we do, we will revise the updated date at the top of this page. We encourage users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect.

You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.

## Contact Us

If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us at:

Noble Kode
Email: privacy@noblekode.com
Website: noblekode.com
`
